### PR TITLE
WIP: Move plotting to blocks-extras

### PR DESCRIPTION
**Pull request by bartvm**

### CODE REVIEW

**Comment by rizar** [comment]
Why did you remove plotting from the examples? I think that for people trying to play with them it can be very useful.

**Comment by bartvm** [comment]
Because it required the merging of https://github.com/mila-udem/blocks/pull/693, a bunch of changes in `.travis.yml` to make the tests not crash (i.e. how are library requirements installed in this repo, etc.) This PR spread amongst 3 repos is annoying enough without sorting all that out, I was planning on performing the move first, and then dotting the i's regarding all the testing later.

**Comment by rizar** [comment]
I am not sure I understand your answer. I just said that having plotting in the examples makes sense, and this PR removes it. If removing it temporarily simplifies dealing with 3 PRs, it is all right, but do you plan to bring it back then?

**Comment by bartvm** [comment]
Yeah.

**Pull request merged**
