### PR TITLE
'params' are now replaced with 'parameters'

### PR DESCRIPTION
**Pull request by mohammadpz**
Following PR in blocks:
https://github.com/mila-udem/blocks/pull/725

### CODE REVIEW

**Comment by bouthilx** [comment]
Why a new PR?

**Comment by mohammadpz** [comment]
Because it's another repo for example. Is there any other way of doing this?

**Comment by bouthilx** [comment]
Ah! Sorry I didn't realized it was blocks-examples and not blocks. My bad!

**Comment by bouthilx** [comment]
Should be good. We'll wait for mila-udem/blocks#725 to be merged and relaunch tests here before we merge.

**Comment by bouthilx** [comment]
@rizar I don't have write access to merge this PR. Can you do it please as you assisted for the PR in blocks.

**Pull request merged**
