### PR TITLE
Replace uses of named_copy with var.copy(name=...)

### PR DESCRIPTION
**Pull request by yingzha**

### CODE REVIEW

**Comment by dmitriy-serdyuk** [comment]
Looks great! There is some weird error with test, I restarted it.

**Comment by dmitriy-serdyuk** [comment]
Seems like a problem with TravisCI. Let's wait until tomorrow, hope they will fix it.

**Comment by nouiz** [comment]
Just a note, This need a very recent change in Theano. So it will force the update of Theano when people update blocks. Do you want that now? Maybe waiting a few weeks would make the transition easier.

**Comment by dmitriy-serdyuk** [comment]
@nouiz , Blocks development cycle is different from Theano. We agreed to make this kind of changes in master branch and have another stable branch. And the main point is to speedup the development process. So, yes, we want this now.

**Comment by dwf** [comment]
I think if you're using bleeding edge master blocks then it is assumed
you're using bleeding edge Theano too.

**Comment by dwf** [comment]
It would be good to send an email to blocks-users mentioning this change
and that it requires updating Theano.

**Comment by nouiz** [comment]
Could you add a try..except and print a good user message to update Theano?
In this case it would be easy to do.

**Comment by rizar** [comment]
Since we can not add such a try-except for each and every Blocks update, I
do not think that we should even try.

However we should be careful about the statu of Blocks-examples repository.
My recent debugging experience with machine translation demo suggests that
the examples will get broken over the time despite the passing tests. This
means that the last compatible version of Fuel and Blocks should be noted.
This in turn means that we can not keep Blocks-examples compatible with
master Blocks...

**Comment by dwf** [comment]
I don't like the idea of freezing blocks-examples in time because the
example was known to work with a given version of blocks. It defeats the
purpose of having examples, which is to teach people how to use blocks as
it exists today -- if we only show them how to use blocks as it once
existed, we've failed.

I think we can make a compromise and manage that with release tags.

Basically we do "releases" of blocks-examples and, on the GitHub
description field for the release (
https://github.com/mila-udem/blocks/releases ) note the hash for Theano,
Fuel and Blocks with which all the examples were last known to work.

**Comment by rizar** [comment]
It is not easy to check that all examples work with particular versions of
Theano, Fuel, Blocks. They come from quite different domains and running
them all would take quite some time.

Maybe in addition to Theano, Blocks and Fuel hashes for every example we
can note the hash of Blocks-examples? This has the benefit that examples
can be developed and tested fully asynchronously.

**Comment by dwf** [comment]
That simplifies things greatly. I like it. (Personally I'd recommend adding
a conda environment specification for the rest of the packages underneath.)

**Comment by rizar** [comment]
Sure, a conda environment would be great. I would require adding one from
people which are not familiar with this piece of software (e.g. myself) to
keep the entry level down.

**Comment by dmitriy-serdyuk** [comment]
I think the PR is harmless, I merge it.

**Comment by madteckhead** [comment]
I think this is the cause of an error when trying to run the demo

(deep_learning)Nathans-MacBook-Pro:deep_learning nathank$ python minst_example.py 
INFO:blocks.algorithms:Taking the cost gradient
INFO:blocks.algorithms:The cost gradient computation graph is built
Traceback (most recent call last):
  File "minst_example.py", line 33, in <module>
    algorithm = GradientDescent(cost=cost, parameters=cg.parameters, step_rule=Scale(learning_rate=0.1))
  File "/Users/nathank/Envs/deep_learning/lib/python2.7/site-packages/blocks/algorithms/__init__.py", line 234, in __init__
    self.gradients.values()).copy(name="total_gradient_norm")
TypeError: copy() got an unexpected keyword argument 'name'

**Comment by rizar** [comment]
Can you please update your Theano?

**Comment by madteckhead** [comment]
Yes. I've done so and I can confirm that it fixed the issues.

On Sun, Jan 3, 2016 at 2:07 AM, Dzmitry Bahdanau <notifications@github.com>
wrote:

> Can you please update your Theano?
>
> On 2 January 2016 at 02:21, Nathan Keilar <notifications@github.com>
> wrote:
>
> > I think this is the cause of an error when trying to run the demo
> >
> > (deep_learning)Nathans-MacBook-Pro:deep_learning nathank$ python
> > minst_example.py
> > INFO:blocks.algorithms:Taking the cost gradient
> > INFO:blocks.algorithms:The cost gradient computation graph is built
> > Traceback (most recent call last):
> > File "minst_example.py", line 33, in
> > algorithm = GradientDescent(cost=cost, parameters=cg.parameters,
> > step_rule=Scale(learning_rate=0.1))
> > File
> >
> "/Users/nathank/Envs/deep_learning/lib/python2.7/site-packages/blocks/algorithms/
> > *init*.py", line 234, in *init*
> > self.gradients.values()).copy(name="total_gradient_norm")
> > TypeError: copy() got an unexpected keyword argument 'name'
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/mila-udem/blocks-examples/pull/40#issuecomment-168368940
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mila-udem/blocks-examples/pull/40#issuecomment-168402230>
> .
>



-- 



Nathan Keilar
Hunted Hive Web Studio ~ Innovative Solutions For Real World Problems
Technical Director and Business Manager

EMAIL:                    nathank@huntedhive.com
PHONE:                  +61 (0) 7 3040 3065 (AUS)
SKYPE/TWITTER:  HuntedHive / https://twitter.com/HuntedHive
FACEBOOK:           *https://www.facebook.com/HuntedHive
<https://www.facebook.com/HuntedHive>*
LINKEDIN:              http://au.linkedin.com/in/nathankeilar
WEB:                       http://huntedhive.com

This email (including any attachments) is confidential and may be
privileged. If you have received it in error, please notify the sender by
return email and delete this message from your system. Any unauthorised use
or dissemination of this message in whole or in part is strictly
prohibited. Please note that emails are susceptible to change and we will
not be liable for the improper or incomplete transmission of the
information contained in this communication nor for any delay in its
receipt or damage to your system. We do not guarantee that the integrity of
this communication has been maintained nor that this communication is free
of viruses, interceptions or interference.

**Pull request merged**
